Social.Web/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Social.Application.Common.Utility;
using Social.Application.Services.Interface;
using Social.Domain.Entities;
using Social.Infrastructure.Data;
using Social.Web.ViewModels;

namespace Social.Web.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly IEmployeeSkillService _employeeSkillService;
        private readonly ITalukService _talukService;
        private readonly ISkillService _skillService;

        public EmployeeController(IEmployeeService employeeService, ITalukService talukService, ISkillService skillService, IEmployeeSkillService employeeSkillService)
        {
            _employeeService = employeeService;
            _talukService = talukService;
            _skillService = skillService;
            _employeeSkillService = employeeSkillService;
        }

        public IActionResult Index()
        {
            var employees = _employeeService.GetEmployeesByUser(User.Identity.Name).ToList();
            return View(employees);
        }

        [Authorize(Policy = SD.Policy_AdminOrDistrictOffier)]
        public IActionResult MasterIndex()
        {
            var empFilterVm = new EmployeeFilterVM();
            return View(empFilterVm);
        }

        [Authorize(Policy = SD.Policy_AdminOrDistrictOffier)]
        [HttpPost]
        public IActionResult MasterIndex(EmployeeFilterVM empFilter)
        {
            var employees = _employeeService.GetAllEmployees();

            if(empFilter.HasOwnHouse != null)
            {
                employees = employees.Where(x => x.HasAHouse.Equals(empFilter.HasOwnHouse));
            }
            if (empFilter.HasSite != null)
            {
                employees = employees.Where(x => x.HasASite.Equals(empFilter.HasSite));
            }
            if (empFilter.HasToilet != null)
            {
                employees = employees.Where(x => x.HasAToilet.Equals(empFilter.HasToilet));
            }
            if (empFilter.HasElectricity != null)
            {
                employees = employees.Where(x => x.HasElectricityConnection.Equals(empFilter.HasElectricity));
            }
            if (empFilter.HasWaterConnection != null)
            {
                employees = employees.Where(x => x.HasWaterConnection.Equals(empFilter.HasWaterConnection));
            }
            if (empFilter.HasSite != null)
            {
                employees = employees.Where(x => x.HasAHouse.Equals(empFilter.HasSite));
            }
            if (empFilter.HasAadharCard != null)
            {
                employees = employees.Where(x => x.HasAadharCard.Equals(empFilter.HasAadharCard));
            }
            if (empFilter.HasAayushmannBharatCard != null)
            {
                employees = employees.Where(x => x.HasAyushmanBharatCard.Equals(empFilter.HasAayushmannBharatCard));
            }
            if (empFilter.HasHealthInsurance != null)
            {
                employees = employees.Where(x => x.HasHealthInsurance.Equals(empFilter.HasHealthInsurance));
            }
            if (empFilter.HasRationCard != null)
            {
                employees = employees.Where(x => x.HasRationCard.Equals(empFilter.HasRationCard));
            }
            if (empFilter.HasNaregaJobCard != null)
            {
                employees = employees.Where(x => x.HasNaregaJobCard.Equals(empFilter.HasNaregaJobCard));
            }

            empFilter.Employees = employees.ToList();
            return View(empFilter);
        }

        public IActionResult Create()
        {
            EmployeeVM employeeVM = new()
            {
                TalukList = GetTalukList(),
                SkillList = GetSkillList()
            };
            return View(employeeVM);
        }

        [HttpPost]
        public IActionResult Create(EmployeeVM employeeVm)
        {
            if (ModelState.IsValid)
            {
                employeeVm.Employee.CreatedBy = User.Identity.Name;
                employeeVm.Employee.CreatedAt = DateTime.Now;
                employeeVm.Employee.ModifiedBy = User.Identity.Name;
                employeeVm.Employee.ModifiedAt = DateTime.Now;
                _employeeService.CreateEmployee(employeeVm.Employee);
                UpdateEmployeeSkills(employeeVm);

                TempData["success"] = "ಮ್ಯಾನ್ಯುಯಲ್ ಸ್ಕ್ಯಾವೆಂಜರ್ಸ್ ಅನ್ನು ಸೇರಿಸಲಾಗಿದೆ";
                return RedirectToAction("Index");
            }
            employeeVm.TalukList = GetTalukList();
            employeeVm.SkillList = GetSkillList();
            return View(employeeVm);

        }
        public IActionResult Update(int employeeId)
        {
            var emp = _employeeService.GetEmployeeById(employeeId);
            EmployeeVM employeeVM = new()
            {
                TalukList = GetTalukList(),
                SkillList = GetSkillList(),
                Employee = emp,
                SelectedSkills = emp.EmployeeSkills.Select(x => x.SkillId).ToList()
            };
            if (employeeVM.Employee == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(employeeVM);
        }

        [HttpPost]
        public IActionResult Update(EmployeeVM employeeVm)
        {
            if (ModelState.IsValid && employeeVm.Employee.EmployeeId > 0)
            {
                employeeVm.Employee.ModifiedBy = User.Identity.Name;
                employeeVm.Employee.ModifiedAt = DateTime.Now;
                _employeeService.UpdateEmployee(employeeVm.Employee);

                _employeeSkillService.DeleteEmployeeSkills(employeeVm.Employee.EmployeeId);
                UpdateEmployeeSkills(employeeVm);

                TempData["success"] = "ಮ್ಯಾನ್ಯುಯಲ್ ಸ್ಕ್ಯಾವೆಂಜರ್ಸ್ ಅನ್ನು ನವೀಕರಿಸಲಾಗಿದೆ";
                return RedirectToAction(nameof(Index));
            }

            employeeVm.TalukList = GetTalukList();
            employeeVm.SkillList = GetSkillList();
            return View(employeeVm);
        }

        public IActionResult Delete(int employeeId)
        {
            var emp = _employeeService.GetEmployeeById(employeeId);
            EmployeeVM employeeVM = new()
            {
                TalukList = GetTalukList(),
                SkillList = GetSkillList(),
                Employee = emp,
                SelectedSkills = emp.EmployeeSkills.Select(x=>x.SkillId).ToList()
            };
            if (employeeVM.Employee == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(employeeVM);
        }

        public IActionResult Details(int employeeId)
        {
            var emp = _employeeService.GetEmployeeById(employeeId);
            EmployeeVM employeeVM = new()
            {
                TalukList = GetTalukList(),
                SkillList = GetSkillList(),
                Employee = emp,
                SelectedSkills = emp.EmployeeSkills.Select(x => x.SkillId).ToList()
            };
            if (employeeVM.Employee == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(employeeVM);
        }

        [Authorize(Policy = SD.Policy_AdminOrDistrictOffier)]
        public IActionResult MasterDetails(int employeeId)
        {
            var emp = _employeeService.GetEmployeeById(employeeId);
            EmployeeVM employeeVM = new()
            {
                TalukList = GetTalukList(),
                SkillList = GetSkillList(),
                Employee = emp,
                SelectedSkills = emp.EmployeeSkills.Select(x => x.SkillId).ToList()
            };
            if (employeeVM.Employee == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(employeeVM);
        }


        [HttpPost]
        public IActionResult Delete(EmployeeVM employeeVm)
        {
            Employee? employee = _employeeService.GetEmployeeById(employeeVm.Employee.EmployeeId);
            if (employee is not null)
            {
                _employeeService.DeleteEmployee(employee.EmployeeId);
                TempData["success"] = "ಮ್ಯಾನ್ಯುಯಲ್ ಸ್ಕ್ಯಾವೆಂಜರ್ಸ್ ಅನ್ನು ಅಳಿಸಲಾಗಿದೆ";
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "Failed to delete the Employee.";
            return View();
        }

        private IEnumerable<SelectListItem> GetTalukList()
        {
            return _talukService.GetAllTaluks().Select(u => new SelectListItem
            {
                Text = u.TalukName,
                Value = u.TalukId.ToString()
            });
        }
        private IEnumerable<SelectListItem> GetSkillList()
        {
            return _skillService.GetAllSkills().Select(u => new SelectListItem
            {
                Text = u.SkillName,
                Value = u.SkillId.ToString()
            });
        }

        private void UpdateEmployeeSkills(EmployeeVM employeeVm)
        {
            if (employeeVm.SelectedSkills != null)
            {
                foreach (var skillId in employeeVm.SelectedSkills)
                {
                    var empSkill = new EmployeeSkill
                    {
                        EmployeeId = employeeVm.Employee.EmployeeId,
                        SkillId = skillId
                    };
                    _employeeSkillService.CreateEmployeeSkill(empSkill);
                }
            }
        }
    }

}

Social.Web/Controllers/FamilyMemberController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Social.Application.Services.Interface;
using Social.Domain.Entities;
using Social.Infrastructure.Data;
using Social.Web.ViewModels;

namespace Social.Web.Controllers
{
    //[Authorize]
    public class FamilyMemberController : Controller
    {
        private readonly IFamilyMemberService _familyMemberService;
        private readonly IEmployeeService _employeeService;

        public FamilyMemberController(IFamilyMemberService familyMemberService, IEmployeeService employeeService)
        {
            _familyMemberService = familyMemberService;
            _employeeService = employeeService;
        }

        public IActionResult Index(int employeeId)
        {
            var familyMembersList = new FamilyMemberListVM();
            List<FamilyMember> familyMembers = new List<FamilyMember>();
            if (employeeId != 0)
            {
                familyMembersList.EmployeeId = employeeId;
                familyMembersList.EmployeeName = _employeeService.GetEmployeeById(employeeId).EmployeeName;
                familyMembers = _familyMemberService.GetFamilyMembers(employeeId).ToList();
            }

            familyMembersList.FamilyMembers = familyMembers;
            return View(familyMembersList);

        }

        public IActionResult Create(int employeeId)
        {
            FamilyMemberVM familyMemberVM = new()
            {
                FamilyMember = new FamilyMember { EmployeeId = employeeId, FamilyMemberName = "" },
                EmployeeList = GetEmployees()
            };
            return View(familyMemberVM);
        }

        [HttpPost]
        public IActionResult Create(FamilyMemberVM familyMemberVm)
        {
            if (ModelState.IsValid)
            {
                familyMemberVm.FamilyMember.CreatedBy = User.Identity.Name;
                familyMemberVm.FamilyMember.CreatedAt = DateTime.Now;
                familyMemberVm.FamilyMember.ModifiedBy = User.Identity.Name;
                familyMemberVm.FamilyMember.ModifiedAt = DateTime.Now;
                _familyMemberService.CreateFamilyMember(familyMemberVm.FamilyMember);
                TempData["success"] = "The Family Member has been created successfully.";
                return RedirectToAction("Index",new {employeeId = familyMemberVm.FamilyMember.EmployeeId});
            }
            familyMemberVm.EmployeeList = GetEmployees();
            return View(familyMemberVm);

        }
        public IActionResult Update(int familyMemberId)
        {
            FamilyMemberVM familyMemberVM = new()
            {
                EmployeeList = GetEmployees(),
                FamilyMember = _familyMemberService.GetFamilyMemberById(familyMemberId)
            };
            if (familyMemberVM.FamilyMember == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(familyMemberVM);
        }

        [HttpPost]
        public IActionResult Update(FamilyMemberVM familyMemberVm)
        {
            if (ModelState.IsValid && familyMemberVm.FamilyMember.FamilyMemberId > 0)
            {
                familyMemberVm.FamilyMember.ModifiedBy = User.Identity.Name;
                familyMemberVm.FamilyMember.ModifiedAt = DateTime.Now;
                _familyMemberService.UpdateFamilyMember(familyMemberVm.FamilyMember);
                TempData["success"] = "The Family Member has been updated successfully.";
                return RedirectToAction("Index", new { employeeId = familyMemberVm.FamilyMember.EmployeeId });
            }
            familyMemberVm.EmployeeList = GetEmployees();
            return View(familyMemberVm);
        }

        public IActionResult Delete(int familyMemberId)
        {

            FamilyMemberVM familyMemberVM = new()
            {
                EmployeeList = GetEmployees(),
                FamilyMember = _familyMemberService.GetFamilyMemberById(familyMemberId)
            };
            if (familyMemberVM.FamilyMember == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(familyMemberVM);
        }


        [HttpPost]
        public IActionResult Delete(FamilyMemberVM familyMemberVm)
        {
            FamilyMember? familyMember = _familyMemberService.GetFamilyMemberById(familyMemberVm.FamilyMember.FamilyMemberId);
            if (familyMember is not null)
            {
                var employeeId = familyMemberVm.FamilyMember.EmployeeId;
                _familyMemberService.DeleteFamilyMember(familyMember.FamilyMemberId);
                TempData["success"] = "The Family Member has been deleted successfully.";
                return RedirectToAction("Index", new { employeeId = employeeId });
            }
            TempData["error"] = "Failed to delete the Family Member.";
            return View();
        }

        private IEnumerable<SelectListItem> GetEmployees()
        {
            return _employeeService.GetAllEmployees().Select(u => new SelectListItem
            {
                Text = u.EmployeeName,
                Value = u.EmployeeId.ToString()
            });
        }
    }
}

Social.Web/Views/Employee/Details.cshtml
@model EmployeeVM

<div class="w-100 card border-0 p-4">
	<div class="card-header bg-success bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">ಮ್ಯಾನ್ಯುಯಲ್ ಸ್ಕ್ಯಾವೆಂಜರ್ಸ್ ವಿವರ</h2>
			</div>
		</div>
	</div>
	<div class="card-body border p-4">
		<form method="post" class="row">
			<input asp-for="Employee.EmployeeId" hidden />
			<div class="row p-3">
				<div class="mb-4">
					<label><strong>ವೈಯಕ್ತಿಕ ವಿವರ</strong></label>
				</div>
				<div class="form-floating py-1 col-12 col-md-6">
					<input asp-for="Employee.EmployeeName" disabled class="form-control border" />
					<label asp-for="Employee.EmployeeName" class="ms-2"></label>
					<span asp-validation-for="Employee.EmployeeName" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12 col-md-6">
					<input asp-for="Employee.IdentityNumber" disabled class="form-control border" />
					<label asp-for="Employee.IdentityNumber" class="ms-2"></label>
					<span asp-validation-for="Employee.IdentityNumber" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12 col-md-6">
					<input asp-for="Employee.Address" disabled class="form-control border" />
					<label asp-for="Employee.Address" class="ms-2"></label>
					<span asp-validation-for="Employee.Address" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12 col-md-6">
					<input asp-for="Employee.Village" disabled class="form-control border" />
					<label asp-for="Employee.Village" class="ms-2"></label>
					<span asp-validation-for="Employee.Village" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12 col-md-6">
					<input asp-for="Employee.VillagePanchayat" disabled class="form-control border" />
					<label asp-for="Employee.VillagePanchayat" class="ms-2"></label>
					<span asp-validation-for="Employee.VillagePanchayat" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12 col-md-6">
					<select disabled asp-for="Employee.TalukId" asp-items="@Model.TalukList"
							class="form-select">
						<option disabled selected>-- ತಾಲ್ಲೂಕು --</option>
					</select>
					<label asp-for="Employee.TalukId" class="ms-2"></label>
					<span asp-validation-for="Employee.TalukId" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12 col-md-6">
					<input asp-for="Employee.BankName" class="form-control border" disabled />
					<label asp-for="Employee.BankName" class="ms-2"></label>
				</div>
				<div class="form-floating py-1 col-12 col-md-6">
					<input asp-for="Employee.BankBranchName" class="form-control border" disabled />
					<label asp-for="Employee.BankBranchName" class="ms-2"></label>
				</div>
				<div class="row mt-4 border-0">
					<div>
						<label><strong>ವಸತಿ ವಿವರ</strong></label>
					</div>
					<div class="form-floating py-1 col-12 col-md-6">
						<div class="checkbox mt-3">
							<input class="form-check-input border" asp-for="Employee.HasAHouse" disabled />
							<label asp-for="Employee.HasAHouse" class="form-label"></label>
						</div>
						<div class="form-floating py-1">
							<input asp-for="Employee.HouseArea" class="form-control border" disabled />
							<label asp-for="Employee.HouseArea" class="ms-2"></label>
							<span asp-validation-for="Employee.HouseArea" class="text-danger"></span>
						</div>
					</div>
					<div class="form-floating py-1 col-12 col-md-6">
						<div class="checkbox mt-3">
							<input class="form-check-input border" asp-for="Employee.AppliedForHouse" disabled />
							<label asp-for="Employee.AppliedForHouse" class="form-label"></label>
						</div>
						<div class="form-floating py-1">
							<input asp-for="Employee.HouseApplicationScheme" disabled class="form-control border" />
							<label asp-for="Employee.HouseApplicationScheme" class="ms-2"></label>
							<span asp-validation-for="Employee.HouseApplicationScheme" class="text-danger"></span>
						</div>
					</div>
					<div class="form-floating py-1 col-12 col-md-6">
						<div class="checkbox mt-3">
							<input class="form-check-input border" asp-for="Employee.HasASite" disabled />
							<label asp-for="Employee.HasASite" class="form-label"></label>
						</div>
						<div class="form-floating py-1">
							<input asp-for="Employee.SiteArea" disabled class="form-control border" />
							<label asp-for="Employee.SiteArea" class="ms-2"></label>
							<span asp-validation-for="Employee.SiteArea" class="text-danger"></span>
						</div>
					</div>
					<div class="form-floating py-1 col-12 col-md-6">
						<div class="checkbox mt-3">
							<input class="form-check-input border" asp-for="Employee.AppliedForSite" disabled />
							<label asp-for="Employee.AppliedForSite" class="form-label"></label>
						</div>
						<div class="form-floating py-1">
							<input asp-for="Employee.SiteApplicationScheme" class="form-control border" disabled />
							<label asp-for="Employee.SiteApplicationScheme" class="ms-2"></label>
							<span asp-validation-for="Employee.SiteApplicationScheme" class="text-danger"></span>
						</div>
					</div>
				</div>

				<div class="border-0">
					<div class="form-floating py-1 row">
						<div class="checkbox mt-3 col-12 col-md-6">
							<input class="form-check-input border" asp-for="Employee.HasAToilet" disabled />
							<label asp-for="Employee.HasAToilet" class="form-label"></label>
						</div>
						<div class="checkbox mt-3 col-12 col-md-6">
							<input class="form-check-input border" asp-for="Employee.HasElectricityConnection" disabled />
							<label asp-for="Employee.HasElectricityConnection" class="form-label"></label>
						</div>
						<div class="checkbox mt-3 col-12 col-md-6">
							<input class="form-check-input border" asp-for="Employee.HasWaterConnection" disabled />
							<label asp-for="Employee.HasWaterConnection" class="form-label"></label>
						</div>
						<div class="checkbox mt-3 col-12 col-md-6">
							<input class="form-check-input border" asp-for="Employee.HasAadharCard" disabled />
							<label asp-for="Employee.HasAadharCard" class="form-label"></label>
						</div>
					</div>
				</div>
				<div class="row mt-4 border-0">
					<div>
						<label><strong>ಆರೋಗ್ಯ / ವಿಮೆ ವಿವರ</strong></label>
					</div>
					<div class="form-floating py-1 col-12 col-md-6">
						<div class="checkbox mt-3">
							<input class="form-check-input border" asp-for="Employee.HasAyushmanBharatCard" disabled />
							<label asp-for="Employee.HasAyushmanBharatCard" class="form-label"></label>
						</div>
						<div class="form-floating py-1">
							<input asp-for="Employee.AyushmanBharatCardNumber" class="form-control border" disabled />
							<label asp-for="Employee.AyushmanBharatCardNumber" class="ms-2"></label>
						</div>
						<div class="checkbox mt-3">
							<input class="form-check-input border" asp-for="Employee.HasHealthInsurance" disabled />
							<label asp-for="Employee.HasHealthInsurance" class="form-label"></label>
						</div>
						<div class="form-floating py-1">
							<input asp-for="Employee.HealthInsuranceName" class="form-control border" disabled />
							<label asp-for="Employee.HealthInsuranceName" class="ms-2"></label>
						</div>
						<div class="checkbox mt-3">
							<input class="form-check-input border" asp-for="Employee.HasRationCard" disabled />
							<label asp-for="Employee.HasRationCard" class="form-label"></label>
						</div>
						<div class="checkbox mt-3">
							<input class="form-check-input border" asp-for="Employee.HasAppliedForRationCard" disabled />
							<label asp-for="Employee.HasAppliedForRationCard" class="form-label"></label>
						</div>
						<div class="checkbox mt-3">
							<input class="form-check-input border" asp-for="Employee.HasNaregaJobCard" disabled />
							<label asp-for="Employee.HasNaregaJobCard" class="form-label"></label>
						</div>
						
					</div>
					<div class="form-floating py-1 col-12 col-md-6">
						<select asp-for="SelectedSkills" multiple asp-items="@Model.SkillList" disabled
								class="form-control" style="height:23rem;">
							<option disabled selected>-- Skills --</option>
						</select>
						<label asp-for="SelectedSkills" class="ms-2"></label>
					</div>
				</div>

				<div class="row pt-2">
					<div class="col-12 col-md-6">
						<a asp-controller="FamilyMember" asp-action="Index" asp-route-employeeId="@Model.Employee.EmployeeId" class="btn btn-success w-100">
							<i class="bi bi-x-circle"></i> ಕುಟುಂಬ ಸದಸ್ಯರು
						</a>
					</div>
					<div class="col-12 col-md-6">
						<a asp-controller="Employee" asp-action="Index" class="btn btn-secondary w-100">
							<i class="bi bi-x-circle"></i> ರದ್ದುಮಾಡಿ
						</a>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

Social.Web/Views/Employee/Index.cshtml
@model IEnumerable<Employee>

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">ಮ್ಯಾನ್ಯುಯಲ್ ಸ್ಕ್ಯಾವೆಂಜರ್ಸ್</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="Employee" asp-action="Create" class="btn btn-secondary">
                    <i class="bi bi-plus-circle"></i> ಮ್ಯಾನ್ಯುಯಲ್ ಸ್ಕ್ಯಾವೆಂಜರ್ಸ್ ಗಳ ಸೇರ್ಪಡೆ
                </a>
            </div>
        </div>

        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        ಹೆಸರು
                    </th>
                    <th>
                        ಐ. ಡಿ. ನಂಬರ್
                    </th>
                    <th>
                        ಗ್ರಾಮ
                    </th>
                    <th>
                        ತಾಲ್ಲೂಕು
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td>@obj.EmployeeName</td>
                        <td>@obj.IdentityNumber</td>
                        <td>@obj.Village</td>
                        <td>@obj.Taluk.TalukName</td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Employee" asp-action="Details" asp-route-employeeId="@obj.EmployeeId"
                                   class="btn btn-success mx-2">
                                    ವಿವರ
                                </a>
                                <a asp-controller="Employee" asp-action="Update" asp-route-employeeId="@obj.EmployeeId"
                                   class="btn btn-success mx-2">
                                    ಮಾರ್ಪಡಿಸು
                                </a>
                                <a asp-controller="Employee" asp-action="Delete" asp-route-employeeId="@obj.EmployeeId"
                                   class="btn btn-danger mx-2">
                                    ಅಳಿಸು
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>